import "~/styles/globals.css";

import { GeistSans } from "geist/font/sans";
import { type Metadata } from "next";

import { TRPCReactProvider } from "~/trpc/react";
import { auth, currentUser } from "@clerk/nextjs/server";
import { db } from "~/server/db";
import { ClerkProvider } from "@clerk/nextjs";
import { Toaster } from "sonner";
import { NavBar } from "~/components/nav-bar";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default async function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  const { userId } = await auth();

  const user = await currentUser();
  if (userId && user) {
    const email_addresses = user.emailAddresses;

    const primaryEmail = email_addresses?.[0]?.emailAddress ?? "";

    try {
      const dbUser = await db.user.findUnique({
        where: { id: userId },
      });

      if (!dbUser) {
        await db.user.create({
          data: {
            id: userId,
            email: primaryEmail || "",
            name: `${user.firstName ?? ""} ${user.lastName ?? ""}`.trim(),
          },
        });
      }
    } catch (error) {
      console.error("An unexpected error occurred:", error);
    }
  }
  return (
    <ClerkProvider>
      <html lang="en" className={`${GeistSans.variable} antialiased`}>
        <body>
          <TRPCReactProvider>
            <Toaster richColors position="top-center" />
            <main className="bg-background flex h-screen flex-col">
              <NavBar />
              {children}
            </main>
          </TRPCReactProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
